language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2.4
  - 2.3.0
script: rspec spec
before_install:
  - gem update bundler
gemfile:
  - Gemfile
  - Gemfile.sidekiq
  - Gemfile.resque
