language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2.4
  - 2.3.0
script: rspec spec
before_install:
  - gem update bundler
gemfile:
  - Gemfile
  - Gemfile.sidekiq
  - Gemfile.resque
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: Gemfile.sidekiq
    - rvm: 2.0.0
      gemfile: Gemfile.sidekiq
    - rvm: 2.1
      gemfile: Gemfile.sidekiq
  include:
    - rvm: 1.9.3
      gemfile: Gemfile.sidekiq.3.1
    - rvm: 2.0.0
      gemfile: Gemfile.sidekiq.3
    - rvm: 2.1
      gemfile: Gemfile.sidekiq.3
